name: Kurt At Work
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24443
title: 'Kurt At Work '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030200'
    - '#2f2c1d'
    - '#e7a95c'
    - '#f5dd9d'
    - '#4d97a4'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
