name: Kurt At Work
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23239
title: Kurt At Work - Phone Repair
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#818181'
    - '#06070b'
    - '#fa0a09'
    - '#02cd98'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
