name: Kurt At Work
favicon: null
layout_spectrum: 0.7339
typography_spectrum: 0.24443
title: 'Kurt At Work '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a4c61'
    - '#e5e8e4'
    - '#d6c4b7'
    - '#8f908e'
    - '#070b0f'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
