name: Kurt At Work
favicon: null
layout_spectrum: 0.2843230478465557
typography_spectrum: 0.4587548163253814
title: Kurt At Work - Phone Repair
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6395779105369002
  lightness: 0.029690335039049387
  saturation: 0.4907279494218528
  rhythmicContrast: 0.9833792429417372
purpose: []
